var Mathdrquinn = {
  login: "Mathdrquinn",
  avatar_url: "https://avatars.githubusercontent.com/u/6947446?v=2",
  name: "Brendan Quinn",
  location: "United States",
  email: "quinn.197@gmail.com",
  public_repos: 8,
  public_gists: 0,
  followers: 10,
  following: 10,
  created_at: "2014-03-14T02:51:14Z",
  cleanDate: new Date ("2014-03-14")
};

var reposArr = [
  {
    "id": 22177366,
    "name": "7.21.14_hw",
    "full_name": "Mathdrquinn/7.21.14_hw",
    "owner": {
      "login": "Mathdrquinn",
      "id": 6947446,
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?v=2",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "html_url": "https://github.com/Mathdrquinn",
      "followers_url": "https://api.github.com/users/Mathdrquinn/followers",
      "following_url": "https://api.github.com/users/Mathdrquinn/following{/other_user}",
      "gists_url": "https://api.github.com/users/Mathdrquinn/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Mathdrquinn/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Mathdrquinn/subscriptions",
      "organizations_url": "https://api.github.com/users/Mathdrquinn/orgs",
      "repos_url": "https://api.github.com/users/Mathdrquinn/repos",
      "events_url": "https://api.github.com/users/Mathdrquinn/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Mathdrquinn/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/Mathdrquinn/7.21.14_hw",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw",
    "forks_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/forks",
    "keys_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/teams",
    "hooks_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/hooks",
    "issue_events_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/events",
    "assignees_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/tags",
    "blobs_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/languages",
    "stargazers_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/stargazers",
    "contributors_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/contributors",
    "subscribers_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/subscribers",
    "subscription_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/subscription",
    "commits_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/merges",
    "archive_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/downloads",
    "issues_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/labels{/name}",
    "releases_url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw/releases{/id}",
    "created_at": "2014-07-23T20:57:24Z",
    "updated_at": "2014-07-23T20:59:18Z",
    "pushed_at": "2014-07-23T20:59:18Z",
    "git_url": "git://github.com/Mathdrquinn/7.21.14_hw.git",
    "ssh_url": "git@github.com:Mathdrquinn/7.21.14_hw.git",
    "clone_url": "https://github.com/Mathdrquinn/7.21.14_hw.git",
    "svn_url": "https://github.com/Mathdrquinn/7.21.14_hw",
    "homepage": null,
    "size": 2588,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 22639453,
    "name": "click_events_and_arrays",
    "full_name": "Mathdrquinn/click_events_and_arrays",
    "owner": {
      "login": "Mathdrquinn",
      "id": 6947446,
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?v=2",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "html_url": "https://github.com/Mathdrquinn",
      "followers_url": "https://api.github.com/users/Mathdrquinn/followers",
      "following_url": "https://api.github.com/users/Mathdrquinn/following{/other_user}",
      "gists_url": "https://api.github.com/users/Mathdrquinn/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Mathdrquinn/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Mathdrquinn/subscriptions",
      "organizations_url": "https://api.github.com/users/Mathdrquinn/orgs",
      "repos_url": "https://api.github.com/users/Mathdrquinn/repos",
      "events_url": "https://api.github.com/users/Mathdrquinn/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Mathdrquinn/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/Mathdrquinn/click_events_and_arrays",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays",
    "forks_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/forks",
    "keys_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/teams",
    "hooks_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/hooks",
    "issue_events_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/events",
    "assignees_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/tags",
    "blobs_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/languages",
    "stargazers_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/stargazers",
    "contributors_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/contributors",
    "subscribers_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/subscribers",
    "subscription_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/subscription",
    "commits_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/merges",
    "archive_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/downloads",
    "issues_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/labels{/name}",
    "releases_url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/releases{/id}",
    "created_at": "2014-08-05T10:17:40Z",
    "updated_at": "2014-08-05T12:26:55Z",
    "pushed_at": "2014-08-05T13:01:46Z",
    "git_url": "git://github.com/Mathdrquinn/click_events_and_arrays.git",
    "ssh_url": "git@github.com:Mathdrquinn/click_events_and_arrays.git",
    "clone_url": "https://github.com/Mathdrquinn/click_events_and_arrays.git",
    "svn_url": "https://github.com/Mathdrquinn/click_events_and_arrays",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 22443580,
    "name": "intro_javascript",
    "full_name": "Mathdrquinn/intro_javascript",
    "owner": {
      "login": "Mathdrquinn",
      "id": 6947446,
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?v=2",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "html_url": "https://github.com/Mathdrquinn",
      "followers_url": "https://api.github.com/users/Mathdrquinn/followers",
      "following_url": "https://api.github.com/users/Mathdrquinn/following{/other_user}",
      "gists_url": "https://api.github.com/users/Mathdrquinn/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Mathdrquinn/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Mathdrquinn/subscriptions",
      "organizations_url": "https://api.github.com/users/Mathdrquinn/orgs",
      "repos_url": "https://api.github.com/users/Mathdrquinn/repos",
      "events_url": "https://api.github.com/users/Mathdrquinn/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Mathdrquinn/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/Mathdrquinn/intro_javascript",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/Mathdrquinn/intro_javascript",
    "forks_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/forks",
    "keys_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/teams",
    "hooks_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/hooks",
    "issue_events_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/events",
    "assignees_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/tags",
    "blobs_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/languages",
    "stargazers_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/stargazers",
    "contributors_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/contributors",
    "subscribers_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/subscribers",
    "subscription_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/subscription",
    "commits_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/merges",
    "archive_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/downloads",
    "issues_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/labels{/name}",
    "releases_url": "https://api.github.com/repos/Mathdrquinn/intro_javascript/releases{/id}",
    "created_at": "2014-07-30T20:33:52Z",
    "updated_at": "2014-07-30T20:51:43Z",
    "pushed_at": "2014-07-30T20:51:43Z",
    "git_url": "git://github.com/Mathdrquinn/intro_javascript.git",
    "ssh_url": "git@github.com:Mathdrquinn/intro_javascript.git",
    "clone_url": "https://github.com/Mathdrquinn/intro_javascript.git",
    "svn_url": "https://github.com/Mathdrquinn/intro_javascript",
    "homepage": null,
    "size": 108,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 22668908,
    "name": "JavaScript_constructors",
    "full_name": "Mathdrquinn/JavaScript_constructors",
    "owner": {
      "login": "Mathdrquinn",
      "id": 6947446,
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?v=2",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "html_url": "https://github.com/Mathdrquinn",
      "followers_url": "https://api.github.com/users/Mathdrquinn/followers",
      "following_url": "https://api.github.com/users/Mathdrquinn/following{/other_user}",
      "gists_url": "https://api.github.com/users/Mathdrquinn/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Mathdrquinn/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Mathdrquinn/subscriptions",
      "organizations_url": "https://api.github.com/users/Mathdrquinn/orgs",
      "repos_url": "https://api.github.com/users/Mathdrquinn/repos",
      "events_url": "https://api.github.com/users/Mathdrquinn/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Mathdrquinn/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/Mathdrquinn/JavaScript_constructors",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors",
    "forks_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/forks",
    "keys_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/teams",
    "hooks_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/hooks",
    "issue_events_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/events",
    "assignees_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/tags",
    "blobs_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/languages",
    "stargazers_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/stargazers",
    "contributors_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/contributors",
    "subscribers_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/subscribers",
    "subscription_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/subscription",
    "commits_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/merges",
    "archive_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/downloads",
    "issues_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/labels{/name}",
    "releases_url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors/releases{/id}",
    "created_at": "2014-08-06T03:51:48Z",
    "updated_at": "2014-08-06T03:53:52Z",
    "pushed_at": "2014-08-06T03:53:52Z",
    "git_url": "git://github.com/Mathdrquinn/JavaScript_constructors.git",
    "ssh_url": "git@github.com:Mathdrquinn/JavaScript_constructors.git",
    "clone_url": "https://github.com/Mathdrquinn/JavaScript_constructors.git",
    "svn_url": "https://github.com/Mathdrquinn/JavaScript_constructors",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 22211753,
    "name": "mimic_homework",
    "full_name": "Mathdrquinn/mimic_homework",
    "owner": {
      "login": "Mathdrquinn",
      "id": 6947446,
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?v=2",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "html_url": "https://github.com/Mathdrquinn",
      "followers_url": "https://api.github.com/users/Mathdrquinn/followers",
      "following_url": "https://api.github.com/users/Mathdrquinn/following{/other_user}",
      "gists_url": "https://api.github.com/users/Mathdrquinn/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Mathdrquinn/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Mathdrquinn/subscriptions",
      "organizations_url": "https://api.github.com/users/Mathdrquinn/orgs",
      "repos_url": "https://api.github.com/users/Mathdrquinn/repos",
      "events_url": "https://api.github.com/users/Mathdrquinn/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Mathdrquinn/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/Mathdrquinn/mimic_homework",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/Mathdrquinn/mimic_homework",
    "forks_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/forks",
    "keys_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/teams",
    "hooks_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/hooks",
    "issue_events_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/events",
    "assignees_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/tags",
    "blobs_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/languages",
    "stargazers_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/stargazers",
    "contributors_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/contributors",
    "subscribers_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/subscribers",
    "subscription_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/subscription",
    "commits_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/merges",
    "archive_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/downloads",
    "issues_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/labels{/name}",
    "releases_url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/releases{/id}",
    "created_at": "2014-07-24T12:17:46Z",
    "updated_at": "2014-07-24T12:26:28Z",
    "pushed_at": "2014-07-25T10:00:25Z",
    "git_url": "git://github.com/Mathdrquinn/mimic_homework.git",
    "ssh_url": "git@github.com:Mathdrquinn/mimic_homework.git",
    "clone_url": "https://github.com/Mathdrquinn/mimic_homework.git",
    "svn_url": "https://github.com/Mathdrquinn/mimic_homework",
    "homepage": null,
    "size": 2632,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 22259514,
    "name": "Mrdrquinn.github.io",
    "full_name": "Mathdrquinn/Mrdrquinn.github.io",
    "owner": {
      "login": "Mathdrquinn",
      "id": 6947446,
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?v=2",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "html_url": "https://github.com/Mathdrquinn",
      "followers_url": "https://api.github.com/users/Mathdrquinn/followers",
      "following_url": "https://api.github.com/users/Mathdrquinn/following{/other_user}",
      "gists_url": "https://api.github.com/users/Mathdrquinn/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Mathdrquinn/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Mathdrquinn/subscriptions",
      "organizations_url": "https://api.github.com/users/Mathdrquinn/orgs",
      "repos_url": "https://api.github.com/users/Mathdrquinn/repos",
      "events_url": "https://api.github.com/users/Mathdrquinn/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Mathdrquinn/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/Mathdrquinn/Mrdrquinn.github.io",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io",
    "forks_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/forks",
    "keys_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/teams",
    "hooks_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/hooks",
    "issue_events_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/events",
    "assignees_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/tags",
    "blobs_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/languages",
    "stargazers_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/stargazers",
    "contributors_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/contributors",
    "subscribers_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/subscribers",
    "subscription_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/subscription",
    "commits_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/merges",
    "archive_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/downloads",
    "issues_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/labels{/name}",
    "releases_url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io/releases{/id}",
    "created_at": "2014-07-25T14:23:05Z",
    "updated_at": "2014-07-25T14:23:05Z",
    "pushed_at": "2014-07-25T14:23:05Z",
    "git_url": "git://github.com/Mathdrquinn/Mrdrquinn.github.io.git",
    "ssh_url": "git@github.com:Mathdrquinn/Mrdrquinn.github.io.git",
    "clone_url": "https://github.com/Mathdrquinn/Mrdrquinn.github.io.git",
    "svn_url": "https://github.com/Mathdrquinn/Mrdrquinn.github.io",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 22557255,
    "name": "photo_album",
    "full_name": "Mathdrquinn/photo_album",
    "owner": {
      "login": "Mathdrquinn",
      "id": 6947446,
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?v=2",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "html_url": "https://github.com/Mathdrquinn",
      "followers_url": "https://api.github.com/users/Mathdrquinn/followers",
      "following_url": "https://api.github.com/users/Mathdrquinn/following{/other_user}",
      "gists_url": "https://api.github.com/users/Mathdrquinn/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Mathdrquinn/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Mathdrquinn/subscriptions",
      "organizations_url": "https://api.github.com/users/Mathdrquinn/orgs",
      "repos_url": "https://api.github.com/users/Mathdrquinn/repos",
      "events_url": "https://api.github.com/users/Mathdrquinn/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Mathdrquinn/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/Mathdrquinn/photo_album",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/Mathdrquinn/photo_album",
    "forks_url": "https://api.github.com/repos/Mathdrquinn/photo_album/forks",
    "keys_url": "https://api.github.com/repos/Mathdrquinn/photo_album/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Mathdrquinn/photo_album/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Mathdrquinn/photo_album/teams",
    "hooks_url": "https://api.github.com/repos/Mathdrquinn/photo_album/hooks",
    "issue_events_url": "https://api.github.com/repos/Mathdrquinn/photo_album/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Mathdrquinn/photo_album/events",
    "assignees_url": "https://api.github.com/repos/Mathdrquinn/photo_album/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Mathdrquinn/photo_album/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Mathdrquinn/photo_album/tags",
    "blobs_url": "https://api.github.com/repos/Mathdrquinn/photo_album/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Mathdrquinn/photo_album/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Mathdrquinn/photo_album/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Mathdrquinn/photo_album/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Mathdrquinn/photo_album/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Mathdrquinn/photo_album/languages",
    "stargazers_url": "https://api.github.com/repos/Mathdrquinn/photo_album/stargazers",
    "contributors_url": "https://api.github.com/repos/Mathdrquinn/photo_album/contributors",
    "subscribers_url": "https://api.github.com/repos/Mathdrquinn/photo_album/subscribers",
    "subscription_url": "https://api.github.com/repos/Mathdrquinn/photo_album/subscription",
    "commits_url": "https://api.github.com/repos/Mathdrquinn/photo_album/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Mathdrquinn/photo_album/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Mathdrquinn/photo_album/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Mathdrquinn/photo_album/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/Mathdrquinn/photo_album/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Mathdrquinn/photo_album/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Mathdrquinn/photo_album/merges",
    "archive_url": "https://api.github.com/repos/Mathdrquinn/photo_album/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Mathdrquinn/photo_album/downloads",
    "issues_url": "https://api.github.com/repos/Mathdrquinn/photo_album/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Mathdrquinn/photo_album/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Mathdrquinn/photo_album/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Mathdrquinn/photo_album/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Mathdrquinn/photo_album/labels{/name}",
    "releases_url": "https://api.github.com/repos/Mathdrquinn/photo_album/releases{/id}",
    "created_at": "2014-08-02T20:54:10Z",
    "updated_at": "2014-08-02T20:54:10Z",
    "pushed_at": "2014-08-02T20:54:10Z",
    "git_url": "git://github.com/Mathdrquinn/photo_album.git",
    "ssh_url": "git@github.com:Mathdrquinn/photo_album.git",
    "clone_url": "https://github.com/Mathdrquinn/photo_album.git",
    "svn_url": "https://github.com/Mathdrquinn/photo_album",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 22574820,
    "name": "photo_album_with_jquery",
    "full_name": "Mathdrquinn/photo_album_with_jquery",
    "owner": {
      "login": "Mathdrquinn",
      "id": 6947446,
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?v=2",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "html_url": "https://github.com/Mathdrquinn",
      "followers_url": "https://api.github.com/users/Mathdrquinn/followers",
      "following_url": "https://api.github.com/users/Mathdrquinn/following{/other_user}",
      "gists_url": "https://api.github.com/users/Mathdrquinn/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Mathdrquinn/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Mathdrquinn/subscriptions",
      "organizations_url": "https://api.github.com/users/Mathdrquinn/orgs",
      "repos_url": "https://api.github.com/users/Mathdrquinn/repos",
      "events_url": "https://api.github.com/users/Mathdrquinn/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Mathdrquinn/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/Mathdrquinn/photo_album_with_jquery",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery",
    "forks_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/forks",
    "keys_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/teams",
    "hooks_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/hooks",
    "issue_events_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/events",
    "assignees_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/tags",
    "blobs_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/languages",
    "stargazers_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/stargazers",
    "contributors_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/contributors",
    "subscribers_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/subscribers",
    "subscription_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/subscription",
    "commits_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/merges",
    "archive_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/downloads",
    "issues_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/labels{/name}",
    "releases_url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery/releases{/id}",
    "created_at": "2014-08-03T12:54:17Z",
    "updated_at": "2014-08-03T13:15:21Z",
    "pushed_at": "2014-08-03T13:15:21Z",
    "git_url": "git://github.com/Mathdrquinn/photo_album_with_jquery.git",
    "ssh_url": "git@github.com:Mathdrquinn/photo_album_with_jquery.git",
    "clone_url": "https://github.com/Mathdrquinn/photo_album_with_jquery.git",
    "svn_url": "https://github.com/Mathdrquinn/photo_album_with_jquery",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 22374397,
    "name": "Responsive_Web_Design",
    "full_name": "Mathdrquinn/Responsive_Web_Design",
    "owner": {
      "login": "Mathdrquinn",
      "id": 6947446,
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?v=2",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "html_url": "https://github.com/Mathdrquinn",
      "followers_url": "https://api.github.com/users/Mathdrquinn/followers",
      "following_url": "https://api.github.com/users/Mathdrquinn/following{/other_user}",
      "gists_url": "https://api.github.com/users/Mathdrquinn/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Mathdrquinn/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Mathdrquinn/subscriptions",
      "organizations_url": "https://api.github.com/users/Mathdrquinn/orgs",
      "repos_url": "https://api.github.com/users/Mathdrquinn/repos",
      "events_url": "https://api.github.com/users/Mathdrquinn/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Mathdrquinn/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/Mathdrquinn/Responsive_Web_Design",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design",
    "forks_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/forks",
    "keys_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/teams",
    "hooks_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/hooks",
    "issue_events_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/events",
    "assignees_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/tags",
    "blobs_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/languages",
    "stargazers_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/stargazers",
    "contributors_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/contributors",
    "subscribers_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/subscribers",
    "subscription_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/subscription",
    "commits_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/merges",
    "archive_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/downloads",
    "issues_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/labels{/name}",
    "releases_url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design/releases{/id}",
    "created_at": "2014-07-29T09:20:17Z",
    "updated_at": "2014-07-29T09:25:49Z",
    "pushed_at": "2014-07-29T09:25:49Z",
    "git_url": "git://github.com/Mathdrquinn/Responsive_Web_Design.git",
    "ssh_url": "git@github.com:Mathdrquinn/Responsive_Web_Design.git",
    "clone_url": "https://github.com/Mathdrquinn/Responsive_Web_Design.git",
    "svn_url": "https://github.com/Mathdrquinn/Responsive_Web_Design",
    "homepage": null,
    "size": 668,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 22250381,
    "name": "transitions",
    "full_name": "Mathdrquinn/transitions",
    "owner": {
      "login": "Mathdrquinn",
      "id": 6947446,
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?v=2",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "html_url": "https://github.com/Mathdrquinn",
      "followers_url": "https://api.github.com/users/Mathdrquinn/followers",
      "following_url": "https://api.github.com/users/Mathdrquinn/following{/other_user}",
      "gists_url": "https://api.github.com/users/Mathdrquinn/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Mathdrquinn/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Mathdrquinn/subscriptions",
      "organizations_url": "https://api.github.com/users/Mathdrquinn/orgs",
      "repos_url": "https://api.github.com/users/Mathdrquinn/repos",
      "events_url": "https://api.github.com/users/Mathdrquinn/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Mathdrquinn/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/Mathdrquinn/transitions",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/Mathdrquinn/transitions",
    "forks_url": "https://api.github.com/repos/Mathdrquinn/transitions/forks",
    "keys_url": "https://api.github.com/repos/Mathdrquinn/transitions/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Mathdrquinn/transitions/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Mathdrquinn/transitions/teams",
    "hooks_url": "https://api.github.com/repos/Mathdrquinn/transitions/hooks",
    "issue_events_url": "https://api.github.com/repos/Mathdrquinn/transitions/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Mathdrquinn/transitions/events",
    "assignees_url": "https://api.github.com/repos/Mathdrquinn/transitions/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Mathdrquinn/transitions/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Mathdrquinn/transitions/tags",
    "blobs_url": "https://api.github.com/repos/Mathdrquinn/transitions/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Mathdrquinn/transitions/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Mathdrquinn/transitions/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Mathdrquinn/transitions/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Mathdrquinn/transitions/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Mathdrquinn/transitions/languages",
    "stargazers_url": "https://api.github.com/repos/Mathdrquinn/transitions/stargazers",
    "contributors_url": "https://api.github.com/repos/Mathdrquinn/transitions/contributors",
    "subscribers_url": "https://api.github.com/repos/Mathdrquinn/transitions/subscribers",
    "subscription_url": "https://api.github.com/repos/Mathdrquinn/transitions/subscription",
    "commits_url": "https://api.github.com/repos/Mathdrquinn/transitions/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Mathdrquinn/transitions/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Mathdrquinn/transitions/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Mathdrquinn/transitions/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/Mathdrquinn/transitions/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Mathdrquinn/transitions/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Mathdrquinn/transitions/merges",
    "archive_url": "https://api.github.com/repos/Mathdrquinn/transitions/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Mathdrquinn/transitions/downloads",
    "issues_url": "https://api.github.com/repos/Mathdrquinn/transitions/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Mathdrquinn/transitions/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Mathdrquinn/transitions/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Mathdrquinn/transitions/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Mathdrquinn/transitions/labels{/name}",
    "releases_url": "https://api.github.com/repos/Mathdrquinn/transitions/releases{/id}",
    "created_at": "2014-07-25T08:36:43Z",
    "updated_at": "2014-07-25T08:40:53Z",
    "pushed_at": "2014-07-25T08:40:53Z",
    "git_url": "git://github.com/Mathdrquinn/transitions.git",
    "ssh_url": "git@github.com:Mathdrquinn/transitions.git",
    "clone_url": "https://github.com/Mathdrquinn/transitions.git",
    "svn_url": "https://github.com/Mathdrquinn/transitions",
    "homepage": null,
    "size": 2652,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  }
];

//I can't believe this mumble of code works.
//age is an empy array made to show that the updates are in order.  It has no other use.
/*var age = [];*/

//This function order reposArr from line 15 by youngest to oldest.  Uses added property ageOld which is added to each object in the array
var order = function (array) {
  //for loop goes through each element
  for (var i = 0; i < array.length; i++) {
    //moment().fromNow() finds the age, .split makes the age an arry whose [0] is the days old of the repo item
    // and the Number() turns that days old into a number to be sorted (can't sort string numbers)
    var ageMoment = Number(moment(array[i].created_at).fromNow().split(' ')[0]);
    //age.push(ageMoment);

    //adds prop with value of age as an int
    array[i].ageOld = ageMoment;
    //console.log(ageMoment);
  }
  //sorting funciton found on
  //https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
  reposArr.sort(function (a, b) {
    if (a.ageOld > b.ageOld)
      return 1;
    if (a.ageOld < b.ageOld)
      return -1;
    // a must be equal to b
    return 0;
});
  //return age;
};

order(reposArr);

var publicArr = [
  {
    "id": "2221112468",
    "type": "CreateEvent",
    "actor": {
      "id": 6947446,
      "login": "Mathdrquinn",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?"
    },
    "repo": {
      "id": 22668908,
      "name": "Mathdrquinn/JavaScript_constructors",
      "url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-08-06T03:53:53Z"
  },
  {
    "id": "2221110881",
    "type": "CreateEvent",
    "actor": {
      "id": 6947446,
      "login": "Mathdrquinn",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?"
    },
    "repo": {
      "id": 22668908,
      "name": "Mathdrquinn/JavaScript_constructors",
      "url": "https://api.github.com/repos/Mathdrquinn/JavaScript_constructors"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-08-06T03:51:48Z"
  },
  {
    "id": "2219627180",
    "type": "PushEvent",
    "actor": {
      "id": 6947446,
      "login": "Mathdrquinn",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?"
    },
    "repo": {
      "id": 22639453,
      "name": "Mathdrquinn/click_events_and_arrays",
      "url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays"
    },
    "payload": {
      "push_id": 422132924,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "1d7c772ad02f9afdd3054a8d294cdd60d81c7d85",
      "before": "1115de4a63bafc2740605e543b226e82a7f55111",
      "commits": [
        {
          "sha": "1d7c772ad02f9afdd3054a8d294cdd60d81c7d85",
          "author": {
            "email": "brendanquinn@Brendans-MacBook-Air.local",
            "name": "Brendan Quinn"
          },
          "message": "Charles is hiding",
          "distinct": true,
          "url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays/commits/1d7c772ad02f9afdd3054a8d294cdd60d81c7d85"
        }
      ]
    },
    "public": true,
    "created_at": "2014-08-05T13:01:46Z"
  },
  {
    "id": "2219571440",
    "type": "CreateEvent",
    "actor": {
      "id": 6947446,
      "login": "Mathdrquinn",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?"
    },
    "repo": {
      "id": 22639453,
      "name": "Mathdrquinn/click_events_and_arrays",
      "url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-08-05T12:26:55Z"
  },
  {
    "id": "2219393010",
    "type": "CreateEvent",
    "actor": {
      "id": 6947446,
      "login": "Mathdrquinn",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?"
    },
    "repo": {
      "id": 22639453,
      "name": "Mathdrquinn/click_events_and_arrays",
      "url": "https://api.github.com/repos/Mathdrquinn/click_events_and_arrays"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-08-05T10:17:40Z"
  },
  {
    "id": "2216521273",
    "type": "CreateEvent",
    "actor": {
      "id": 6947446,
      "login": "Mathdrquinn",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?"
    },
    "repo": {
      "id": 22574820,
      "name": "Mathdrquinn/photo_album_with_jquery",
      "url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-08-03T13:15:21Z"
  },
  {
    "id": "2216512932",
    "type": "CreateEvent",
    "actor": {
      "id": 6947446,
      "login": "Mathdrquinn",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?"
    },
    "repo": {
      "id": 22574820,
      "name": "Mathdrquinn/photo_album_with_jquery",
      "url": "https://api.github.com/repos/Mathdrquinn/photo_album_with_jquery"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-08-03T12:54:17Z"
  },
  {
    "id": "2216165262",
    "type": "CreateEvent",
    "actor": {
      "id": 6947446,
      "login": "Mathdrquinn",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?"
    },
    "repo": {
      "id": 22557255,
      "name": "Mathdrquinn/photo_album",
      "url": "https://api.github.com/repos/Mathdrquinn/photo_album"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-08-02T20:54:11Z"
  },
  {
    "id": "2211409058",
    "type": "CreateEvent",
    "actor": {
      "id": 6947446,
      "login": "Mathdrquinn",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?"
    },
    "repo": {
      "id": 22443580,
      "name": "Mathdrquinn/intro_javascript",
      "url": "https://api.github.com/repos/Mathdrquinn/intro_javascript"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-07-30T20:51:43Z"
  },
  {
    "id": "2211373849",
    "type": "CreateEvent",
    "actor": {
      "id": 6947446,
      "login": "Mathdrquinn",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?"
    },
    "repo": {
      "id": 22443580,
      "name": "Mathdrquinn/intro_javascript",
      "url": "https://api.github.com/repos/Mathdrquinn/intro_javascript"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-07-30T20:33:52Z"
  },
  {
    "id": "2208005062",
    "type": "CreateEvent",
    "actor": {
      "id": 6947446,
      "login": "Mathdrquinn",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?"
    },
    "repo": {
      "id": 22374397,
      "name": "Mathdrquinn/Responsive_Web_Design",
      "url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-07-29T09:25:49Z"
  },
  {
    "id": "2207996592",
    "type": "CreateEvent",
    "actor": {
      "id": 6947446,
      "login": "Mathdrquinn",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?"
    },
    "repo": {
      "id": 22374397,
      "name": "Mathdrquinn/Responsive_Web_Design",
      "url": "https://api.github.com/repos/Mathdrquinn/Responsive_Web_Design"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-07-29T09:20:17Z"
  },
  {
    "id": "2203494615",
    "type": "CreateEvent",
    "actor": {
      "id": 6947446,
      "login": "Mathdrquinn",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?"
    },
    "repo": {
      "id": 22259514,
      "name": "Mathdrquinn/Mrdrquinn.github.io",
      "url": "https://api.github.com/repos/Mathdrquinn/Mrdrquinn.github.io"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-07-25T14:23:05Z"
  },
  {
    "id": "2203131595",
    "type": "PushEvent",
    "actor": {
      "id": 6947446,
      "login": "Mathdrquinn",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?"
    },
    "repo": {
      "id": 22211753,
      "name": "Mathdrquinn/mimic_homework",
      "url": "https://api.github.com/repos/Mathdrquinn/mimic_homework"
    },
    "payload": {
      "push_id": 414849528,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "5273947750459b455131e7722277159dcbf72b72",
      "before": "44d52f894c4219c78438a219be6f3faf14ebd7aa",
      "commits": [
        {
          "sha": "5273947750459b455131e7722277159dcbf72b72",
          "author": {
            "email": "brendanquinn@brendans-air.attlocal.net",
            "name": "Brendan Quinn"
          },
          "message": "Final uptoad 2",
          "distinct": true,
          "url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/commits/5273947750459b455131e7722277159dcbf72b72"
        }
      ]
    },
    "public": true,
    "created_at": "2014-07-25T10:00:25Z"
  },
  {
    "id": "2203029463",
    "type": "PushEvent",
    "actor": {
      "id": 6947446,
      "login": "Mathdrquinn",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?"
    },
    "repo": {
      "id": 22211753,
      "name": "Mathdrquinn/mimic_homework",
      "url": "https://api.github.com/repos/Mathdrquinn/mimic_homework"
    },
    "payload": {
      "push_id": 414802480,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "44d52f894c4219c78438a219be6f3faf14ebd7aa",
      "before": "4b2cafcf5662ef3036d4007aaa5a11ad3cf08c70",
      "commits": [
        {
          "sha": "44d52f894c4219c78438a219be6f3faf14ebd7aa",
          "author": {
            "email": "brendanquinn@brendans-air.attlocal.net",
            "name": "Brendan Quinn"
          },
          "message": "Final",
          "distinct": true,
          "url": "https://api.github.com/repos/Mathdrquinn/mimic_homework/commits/44d52f894c4219c78438a219be6f3faf14ebd7aa"
        }
      ]
    },
    "public": true,
    "created_at": "2014-07-25T08:43:57Z"
  },
  {
    "id": "2203025613",
    "type": "CreateEvent",
    "actor": {
      "id": 6947446,
      "login": "Mathdrquinn",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?"
    },
    "repo": {
      "id": 22250381,
      "name": "Mathdrquinn/transitions",
      "url": "https://api.github.com/repos/Mathdrquinn/transitions"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-07-25T08:40:53Z"
  },
  {
    "id": "2203020520",
    "type": "CreateEvent",
    "actor": {
      "id": 6947446,
      "login": "Mathdrquinn",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?"
    },
    "repo": {
      "id": 22250381,
      "name": "Mathdrquinn/transitions",
      "url": "https://api.github.com/repos/Mathdrquinn/transitions"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-07-25T08:36:43Z"
  },
  {
    "id": "2201380887",
    "type": "CreateEvent",
    "actor": {
      "id": 6947446,
      "login": "Mathdrquinn",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?"
    },
    "repo": {
      "id": 22211753,
      "name": "Mathdrquinn/mimic_homework",
      "url": "https://api.github.com/repos/Mathdrquinn/mimic_homework"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-07-24T12:26:29Z"
  },
  {
    "id": "2201369104",
    "type": "CreateEvent",
    "actor": {
      "id": 6947446,
      "login": "Mathdrquinn",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?"
    },
    "repo": {
      "id": 22211753,
      "name": "Mathdrquinn/mimic_homework",
      "url": "https://api.github.com/repos/Mathdrquinn/mimic_homework"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-07-24T12:17:46Z"
  },
  {
    "id": "2200333525",
    "type": "CreateEvent",
    "actor": {
      "id": 6947446,
      "login": "Mathdrquinn",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?"
    },
    "repo": {
      "id": 22177366,
      "name": "Mathdrquinn/7.21.14_hw",
      "url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-07-23T20:59:19Z"
  },
  {
    "id": "2200329858",
    "type": "CreateEvent",
    "actor": {
      "id": 6947446,
      "login": "Mathdrquinn",
      "gravatar_id": "92a644d790edb5fe37fdf6f17ab41154",
      "url": "https://api.github.com/users/Mathdrquinn",
      "avatar_url": "https://avatars.githubusercontent.com/u/6947446?"
    },
    "repo": {
      "id": 22177366,
      "name": "Mathdrquinn/7.21.14_hw",
      "url": "https://api.github.com/repos/Mathdrquinn/7.21.14_hw"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2014-07-23T20:57:24Z"
  }
]
